export const rioDasOstras = [
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Alphaville' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Âncora' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Atlântica' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Balneário das Garças' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Balneário Remanso' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Boca da Barra' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Bosque Beira Rio' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Bosque da Areia' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Bosque da Praia' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Cantagalo' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Cantinho do Mar' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Casa Grande' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Centro' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Chácara Mariléa' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Cidade Beira Mar' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Cidade Praiana' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Colinas' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Costazul' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Enseada das Gaivotas' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Extensão do Bosque' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Extensão Novo Rio das Ostras' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Extensão Serramar' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Fazenda Palmeiras' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Floresta das Gaivotas' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Gelson Apicelo' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Jardim Bela Vista' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Jardim Campomar' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Jardim Mariléa' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Jardim Miramar' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Jardim Patrícia' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Liberdade' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Loteamento Atlântica' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Mar do Norte' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Nova Aliança' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Nova Cidade' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Nova Esperança' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Novo Rio das Ostras' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Ouro Verde' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Palmital' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Parque São Jorge' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Parque Zabulão' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Peroba' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Porto Seguro' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Praiamar' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Recanto' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Recreio' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Reduto da Paz' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Residencial Camping do Bosque' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Residencial Maria Turri' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Residencial Praia Âncora' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Residencial Rio das Ostras' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Residencial Verdes Mares' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Rocha Leão' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Serramar' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Sobradinho/Cerveja' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'São Cristóvão' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Terra Firme' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Vila Real' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Vila Verde' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Village Rio das Ostras' },
  { state: 'RJ', city: 'Rio das Ostras', neighborhood: 'Village Sol e Mar' }
]
